### ISSUE TITLE
Pressing reset while micro:bit is connected to jacdac-ts causes a disconnect

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#348]
**Describe the bug**
Pressing the reset button on the micro:bit seemingly causes jacdac-ts site to break. The micro:bit device disconnects and does not reappear

**To Reproduce**
1. Flash a program to micro:bit with modules.identify()
2. Go to aka.ms/jacdac and hit connect
3. reset the micro:bit (more than once might be required)
3. See the site get confused.

**Comment by pelikhan** [comment]
Could you copy the output of the javascript console when this happens?

**Comment by pelikhan** [comment]
I pushed a fix https://github.com/microsoft/jacdac-ts/commit/221732e46e32e43ab207af725edbaa4ba00e36a4 Can you try it out?

**Comment by pelikhan** [comment]
Please test to see if it works to your taste.

**Comment by pelikhan** [comment]
Reopen if still an issue.

**Comment by jamesadevine** [comment]
It doesn't seem to have changed anything on my side. I'll assume that this is because the site hasn't yet updated. What's the best way to get the latest version for sure?

**Comment by pelikhan** [comment]
You'll see the short sha in the footer which you can compare to the jacdac-docs repo.

**Comment by jamesadevine** [comment]
Pressing reset whilst the micro:bit is connected (a couple of times) still breaks the website with sha 7b14eaea.

I am using the attached hex file with a micro:bit V2.
[microbit-enumeration-test (11).hex.zip](https://github.com/microsoft/jacdac/files/6364727/microbit-enumeration-test.11.hex.zip)

**Comment by pelikhan** [comment]
Can you add ?dbg=1 to the web site and copy the JavaScript console output.

What does break mean?

________________________________

**Comment by jamesadevine** [comment]
Jacdac site drops connection to the micro:bit and does not try to reconnect. Will add the dbg flag!

**Comment by jamesadevine** [comment]
```
usb: exchange address: 0x200063e8; irqn=12
bus.ts:206 bus: connect USB connected Object
three.module.js:18162 THREE.WebGLRenderer: Context Lost.
transport.ts:195 error USB device "BBC micro:bit CMSIS-DAP" (bad response, 0 != 14 && 0 != 1)
Error: device "BBC micro:bit CMSIS-DAP" (bad response, 0 != 14 && 0 != 1)
    at Transport.error (https://microsoft.github.io/jacdac-docs/app-e8ed9929e852189e1d46.js:45415:18)
    at CMSISProto.error (https://microsoft.github.io/jacdac-docs/app-e8ed9929e852189e1d46.js:44050:78)
    at _callee9$ (https://microsoft.github.io/jacdac-docs/app-e8ed9929e852189e1d46.js:44672:73)
    at tryCatch (https://microsoft.github.io/jacdac-docs/app-e8ed9929e852189e1d46.js:49952:40)
    at Generator.invoke [as _invoke] (https://microsoft.github.io/jacdac-docs/app-e8ed9929e852189e1d46.js:50182:22)
    at Generator.next (https://microsoft.github.io/jacdac-docs/app-e8ed9929e852189e1d46.js:50007:21)
    at asyncGeneratorStep (https://microsoft.github.io/jacdac-docs/app-e8ed9929e852189e1d46.js:77:24)
    at _next (https://microsoft.github.io/jacdac-docs/app-e8ed9929e852189e1d46.js:99:9)
errorHandler @ transport.ts:195
transport.onError @ usb.ts:103
error @ hf2.ts:200
error @ microbit.ts:59
_callee9$ @ microbit.ts:331
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ utils.ts:238
(anonymous) @ utils.ts:249
enqueue @ utils.ts:227
_callee10$ @ microbit.ts:314
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
writeWords @ microbit.ts:19
writeWord @ microbit.ts:426
_callee4$ @ microbit.ts:190
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
eventsource.ts:117 {context: "USB", exception: Error: device "BBC micro:bit CMSIS-DAP" (bad response, 0 != 14 && 0 != 1)
    at Transport.error (h…}
emit @ eventsource.ts:117
errorHandler @ transport.ts:198
transport.onError @ usb.ts:103
error @ hf2.ts:200
error @ microbit.ts:59
_callee9$ @ microbit.ts:331
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ utils.ts:238
(anonymous) @ utils.ts:249
enqueue @ utils.ts:227
_callee10$ @ microbit.ts:314
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
writeWords @ microbit.ts:19
writeWord @ microbit.ts:426
_callee4$ @ microbit.ts:190
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
three.module.js:18162 THREE.WebGLRenderer: Context Lost.
```

**Comment by pelikhan** [comment]
Fixed by https://github.com/microsoft/jacdac-docs/commit/a1ecd4cd63f02c9a88fa9f553be1157fe7a35ad4
