### ISSUE TITLE
Cannot connect to Jacdac bus via USB

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#359]
**Describe the bug**
When attempting to connect to my device over usb, the jacdac website gives the following error:
```
error USB device  (Error: Timeout)
Error: device  (Error: Timeout)
    at Transport.error (https://microsoft.github.io/jacdac-docs/app-11055cab68451b363192.js:44817:18)
    at HF2Proto.error (https://microsoft.github.io/jacdac-docs/app-11055cab68451b363192.js:45227:20)
    at https://microsoft.github.io/jacdac-docs/app-11055cab68451b363192.js:45284:16
errorHandler @ transport.ts:196
transport.onError @ usb.ts:102
error @ hf2.ts:200
error @ hf2.ts:425
(anonymous) @ hf2.ts:475
Promise.catch (async)
handleReturnAsync @ hf2.ts:441
Promise.then (async)
(anonymous) @ hf2.ts:480
(anonymous) @ utils.ts:238
(anonymous) @ utils.ts:249
enqueue @ utils.ts:227
talkAsync @ hf2.ts:479
_callee7$ @ hf2.ts:547
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
checkMode @ app-11055cab68451b363192.js:45451
_callee6$ @ hf2.ts:540
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
postConnectAsync @ app-11055cab68451b363192.js:45391
_callee4$ @ hf2.ts:340
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
connectAsync @ hf2.ts:113
_callee2$ @ usb.ts:111
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
transportConnectAsync @ app-11055cab68451b363192.js:45700
(anonymous) @ transport.ts:122
Promise.then (async)
connect @ transport.ts:121
ConnectButton.onClick @ ConnectButton.tsx:35
Rb @ react-dom.production.min.js:52
Xb @ react-dom.production.min.js:52
Yb @ react-dom.production.min.js:53
Ze @ react-dom.production.min.js:100
se @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Jb @ react-dom.production.min.js:292
Nb @ react-dom.production.min.js:50
jd @ react-dom.production.min.js:105
yc @ react-dom.production.min.js:75
hd @ react-dom.production.min.js:74
push.60053.exports.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
Hb @ react-dom.production.min.js:292
gd @ react-dom.production.min.js:73
eventsource.ts:131 {context: "USB", exception: Error: device  (Error: Timeout)
    at Transport.error (https://microsoft.github.io/jacdac-docs/app…}
```
```
{context: "USB", exception: Error: device  (Error: Timeout)
    at Transport.error (https://microsoft.github.io/jacdac-docs/app…}
context: "USB"
exception: Error: device (Error: Timeout) at Transport.error (https://microsoft.github.io/jacdac-docs/app-11055cab68451b363192.js:44817:18) at HF2Proto.error (https://microsoft.github.io/jacdac-docs/app-11055cab68451b363192.js:45227:20) at https://microsoft.github.io/jacdac-docs/app-11055cab68451b363192.js:45284:16
__proto__: Object
```

I am testing a new microcontroller, so it is possible that something is going awry on the microcontroller. USB trace seems good, and the microcontroller is responding appropriately (I think)

**Comment by jamesadevine** [comment]
@mmoskal is there a tool that I can use to isolate whether webusb is the issue or if the issue is more fundamental?

**Comment by jamesadevine** [comment]
Seems like a config issue on my side.

**Comment by pelikhan** [comment]
Closing. Reopen if more issues.
