### ISSUE TITLE
error in jacdac extension

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#768]
- start new project
- add jacdac extension
- see compile error: cannot read properties undefined (reading _setLedChannel)

![image](https://user-images.githubusercontent.com/10767146/135964619-fb98bd23-60bf-41dd-a532-153b026234e2.png)

**Comment by tballmsft** [comment]
pxtapp.js:1 
        
       Cannot read properties of undefined (reading '_setLedChannel')
   at setLed (pxt_modules/jacdac/routing.ts:1467:5)
   at <main> (main.ts:1:1)

**Comment by tballmsft** [comment]
pxtsim.js:1 
        
       Simulator crashed, no error handler TypeError: Cannot read properties of undefined (reading '_setLedChannel')
    at Object.jacdac_setLed__P6226 [as fn] (eval at Runtime (https://pxt.azureedge.net/blob/4d2d8d7e0317df99b786e40760f31a769b6d0aea/pxtsim.js:1:79866), <anonymous>:18295:23)
    at loop (https://pxt.azureedge.net/blob/4d2d8d7e0317df99b786e40760f31a769b6d0aea/pxtsim.js:1:77294)
    at https://pxt.azureedge.net/blob/4d2d8d7e0317df99b786e40760f31a769b6d0aea/pxtsim.js:1:74746

**Comment by tballmsft** [comment]
there is no implementation in .ts of _setLedChannel

    //% shim=jacdac::_setLedChannel
    declare function _setLedChannel(ch: number, val: number): void

**Comment by pelikhan** [comment]
Fixed in 0.7.5
