### ISSUE TITLE
module tester handing on our LED ring

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#982]
![image](https://user-images.githubusercontent.com/10767146/165358976-68c9aebf-7f4a-453f-8ec9-17bda59354d6.png)

**Comment by tballmsft** [comment]
Trace:
```
useAnalytics.ts:140 
        
       Uncaught error:  {componentStack: '\n    at DashboardLED (https://microsoft.github.io/…acdac-docs/app-1a47cce621c3ef2aac65.js:41312:391)'}
componentDidCatch @ useAnalytics.ts:140
Fi.f.componentDidCatch.c.callback @ react-dom.production.min.js:187
Ag @ react-dom.production.min.js:137
ak @ react-dom.production.min.js:260
Yj @ react-dom.production.min.js:259
Xj @ react-dom.production.min.js:258
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
uk @ react-dom.production.min.js:272
dg @ react-dom.production.min.js:127
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
wk @ react-dom.production.min.js:270
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
DbContext.tsx:303 db: indexeddb
react-dom.production.min.js:186 
        
       
Ai @ react-dom.production.min.js:186
Fi.f.componentDidCatch.c.callback @ react-dom.production.min.js:187
Ag @ react-dom.production.min.js:137
ak @ react-dom.production.min.js:260
Yj @ react-dom.production.min.js:259
Xj @ react-dom.production.min.js:258
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
uk @ react-dom.production.min.js:272
dg @ react-dom.production.min.js:127
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
wk @ react-dom.production.min.js:270
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
useAnalytics.ts:140 
        
       Uncaught error:  {componentStack: '\n    at DashboardLED (https://microsoft.github.io/…acdac-docs/app-1a47cce621c3ef2aac65.js:41312:391)'}
componentDidCatch @ useAnalytics.ts:140
Fi.f.componentDidCatch.c.callback @ react-dom.production.min.js:187
Ag @ react-dom.production.min.js:137
ak @ react-dom.production.min.js:260
Yj @ react-dom.production.min.js:259
Xj @ react-dom.production.min.js:258
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
uk @ react-dom.production.min.js:272
dg @ react-dom.production.min.js:127
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
wk @ react-dom.production.min.js:270
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
DbContext.tsx:303 db: indexeddb
react-dom.production.min.js:186 
        
       
Ai @ react-dom.production.min.js:186
Fi.f.componentDidCatch.c.callback @ react-dom.production.min.js:187
Ag @ react-dom.production.min.js:137
ak @ react-dom.production.min.js:260
Yj @ react-dom.production.min.js:259
Xj @ react-dom.production.min.js:258
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
uk @ react-dom.production.min.js:272
dg @ react-dom.production.min.js:127
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
wk @ react-dom.production.min.js:270
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
useAnalytics.ts:140 
        
       Uncaught error:  {componentStack: '\n    at DashboardLED (https://microsoft.github.io/…acdac-docs/app-1a47cce621c3ef2aac65.js:41312:391)'}
componentDidCatch @ useAnalytics.ts:140
Fi.f.componentDidCatch.c.callback @ react-dom.production.min.js:187
Ag @ react-dom.production.min.js:137
ak @ react-dom.production.min.js:260
Yj @ react-dom.production.min.js:259
Xj @ react-dom.production.min.js:258
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
uk @ react-dom.production.min.js:272
dg @ react-dom.production.min.js:127
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
wk @ react-dom.production.min.js:270
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
DbContext.tsx:303 db: indexeddb
react-dom.production.min.js:186 
        
       
Ai @ react-dom.production.min.js:186
Fi.f.componentDidCatch.c.callback @ react-dom.production.min.js:187
Ag @ react-dom.production.min.js:137
ak @ react-dom.production.min.js:260
Yj @ react-dom.production.min.js:259
Xj @ react-dom.production.min.js:258
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
uk @ react-dom.production.min.js:272
dg @ react-dom.production.min.js:127
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
wk @ react-dom.production.min.js:270
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
useAnalytics.ts:140 
        
       Uncaught error:  {componentStack: '\n    at DashboardLED (https://microsoft.github.io/…acdac-docs/app-1a47cce621c3ef2aac65.js:41312:391)'}
componentDidCatch @ useAnalytics.ts:140
Fi.f.componentDidCatch.c.callback @ react-dom.production.min.js:187
Ag @ react-dom.production.min.js:137
ak @ react-dom.production.min.js:260
Yj @ react-dom.production.min.js:259
Xj @ react-dom.production.min.js:258
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
uk @ react-dom.production.min.js:272
dg @ react-dom.production.min.js:127
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
wk @ react-dom.production.min.js:270
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
DbContext.tsx:303 db: indexeddb
react-dom.production.min.js:186 
        
       
Ai @ react-dom.production.min.js:186
Fi.f.componentDidCatch.c.callback @ react-dom.production.min.js:187
Ag @ react-dom.production.min.js:137
ak @ react-dom.production.min.js:260
Yj @ react-dom.production.min.js:259
Xj @ react-dom.production.min.js:258
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
uk @ react-dom.production.min.js:272
dg @ react-dom.production.min.js:127
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
wk @ react-dom.production.min.js:270
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
useAnalytics.ts:140 
        
       Uncaught error:  {componentStack: '\n    at DashboardLED (https://microsoft.github.io/…acdac-docs/app-1a47cce621c3ef2aac65.js:41312:391)'}
componentDidCatch @ useAnalytics.ts:140
Fi.f.componentDidCatch.c.callback @ react-dom.production.min.js:187
Ag @ react-dom.production.min.js:137
ak @ react-dom.production.min.js:260
Yj @ react-dom.production.min.js:259
Xj @ react-dom.production.min.js:258
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
uk @ react-dom.production.min.js:272
dg @ react-dom.production.min.js:127
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
wk @ react-dom.production.min.js:270
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
DbContext.tsx:303 db: indexeddb
react-dom.production.min.js:186 
        
       
Ai @ react-dom.production.min.js:186
Fi.f.componentDidCatch.c.callback @ react-dom.production.min.js:187
Ag @ react-dom.production.min.js:137
ak @ react-dom.production.min.js:260
Yj @ react-dom.production.min.js:259
Xj @ react-dom.production.min.js:258
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
uk @ react-dom.production.min.js:272
dg @ react-dom.production.min.js:127
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
wk @ react-dom.production.min.js:270
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
useAnalytics.ts:140 
        
       Uncaught error:  {componentStack: '\n    at DashboardLED (https://microsoft.github.io/…acdac-docs/app-1a47cce621c3ef2aac65.js:41312:391)'}
componentDidCatch @ useAnalytics.ts:140
Fi.f.componentDidCatch.c.callback @ react-dom.production.min.js:187
Ag @ react-dom.production.min.js:137
ak @ react-dom.production.min.js:260
Yj @ react-dom.production.min.js:259
Xj @ react-dom.production.min.js:258
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
uk @ react-dom.production.min.js:272
dg @ react-dom.production.min.js:127
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
wk @ react-dom.production.min.js:270
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
DbContext.tsx:303 db: indexeddb
react-dom.production.min.js:186 
        
       
Ai @ react-dom.production.min.js:186
Fi.f.componentDidCatch.c.callback @ react-dom.production.min.js:187
Ag @ react-dom.production.min.js:137
ak @ react-dom.production.min.js:260
Yj @ react-dom.production.min.js:259
Xj @ react-dom.production.min.js:258
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
uk @ react-dom.production.min.js:272
dg @ react-dom.production.min.js:127
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
wk @ react-dom.production.min.js:270
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
useAnalytics.ts:140 
        
       Uncaught error:  {componentStack: '\n    at DashboardLED (https://microsoft.github.io/…acdac-docs/app-1a47cce621c3ef2aac65.js:41312:391)'}
componentDidCatch @ useAnalytics.ts:140
Fi.f.componentDidCatch.c.callback @ react-dom.production.min.js:187
Ag @ react-dom.production.min.js:137
ak @ react-dom.production.min.js:260
Yj @ react-dom.production.min.js:259
Xj @ react-dom.production.min.js:258
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
uk @ react-dom.production.min.js:272
dg @ react-dom.production.min.js:127
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
wk @ react-dom.production.min.js:270
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
DbContext.tsx:303 db: indexeddb
react-dom.production.min.js:186 
        
       
Ai @ react-dom.production.min.js:186
Fi.f.componentDidCatch.c.callback @ react-dom.production.min.js:187
Ag @ react-dom.production.min.js:137
ak @ react-dom.production.min.js:260
Yj @ react-dom.production.min.js:259
Xj @ react-dom.production.min.js:258
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
uk @ react-dom.production.min.js:272
dg @ react-dom.production.min.js:127
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
wk @ react-dom.production.min.js:270
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
useAnalytics.ts:140 
        
       Uncaught error:  {componentStack: '\n    at DashboardLED (https://microsoft.github.io/…acdac-docs/app-1a47cce621c3ef2aac65.js:41312:391)'}
componentDidCatch @ useAnalytics.ts:140
Fi.f.componentDidCatch.c.callback @ react-dom.production.min.js:187
Ag @ react-dom.production.min.js:137
ak @ react-dom.production.min.js:260
Yj @ react-dom.production.min.js:259
Xj @ react-dom.production.min.js:258
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
uk @ react-dom.production.min.js:272
dg @ react-dom.production.min.js:127
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
wk @ react-dom.production.min.js:270
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
DbContext.tsx:303 db: indexeddb
react-dom.production.min.js:186 
        
       
Ai @ react-dom.production.min.js:186
Fi.f.componentDidCatch.c.callback @ react-dom.production.min.js:187
Ag @ react-dom.production.min.js:137
ak @ react-dom.production.min.js:260
Yj @ react-dom.production.min.js:259
Xj @ react-dom.production.min.js:258
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
uk @ react-dom.production.min.js:272
dg @ react-dom.production.min.js:127
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
wk @ react-dom.production.min.js:270
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
useAnalytics.ts:140 
        
       Uncaught error:  {componentStack: '\n    at DashboardLED (https://microsoft.github.io/…acdac-docs/app-1a47cce621c3ef2aac65.js:41312:391)'}
componentDidCatch @ useAnalytics.ts:140
Fi.f.componentDidCatch.c.callback @ react-dom.production.min.js:187
Ag @ react-dom.production.min.js:137
ak @ react-dom.production.min.js:260
Yj @ react-dom.production.min.js:259
Xj @ react-dom.production.min.js:258
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
uk @ react-dom.production.min.js:272
dg @ react-dom.production.min.js:127
Mk @ react-dom.production.min.js:282
Fk @ react-dom.production.min.js:280
wk @ react-dom.production.min.js:270
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
DbContext.tsx:303 db: indexeddb
```

**Comment by tballmsft** [comment]
Dashboard is hanging too - it's the LED ring, not the module tester:

![image](https://user-images.githubusercontent.com/10767146/165360182-e5dd248e-019a-4662-a231-3d1b78c91ff1.png)
